magnuscolors/misset-addons

misset_account/__init__.py
misset_account/__manifest__.py
misset_account/controllers/__init__.py
misset_account/controllers/controllers.py
misset_account/demo/demo.xml
misset_account/models/__init__.py
misset_account/models/models.py
misset_account/report/report_invoice.xml
misset_account/security/ir.model.access.csv
misset_account/views/templates.xml
misset_account/views/views.xml

Task: T0169 - Finalize Misset invoice report
Module: misset_account

Task: T0169 - Finalize Misset invoice report

---

nsm_sale_advertising_order/__init__.py
nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/data/circulation_type.xml
nsm_sale_advertising_order/data/data.xml
nsm_sale_advertising_order/i18n/nl.po
nsm_sale_advertising_order/models/__init__.py
nsm_sale_advertising_order/models/advertising_issue.py
nsm_sale_advertising_order/models/circulation_type.py
nsm_sale_advertising_order/models/credit_control_run.py
nsm_sale_advertising_order/models/product.py
nsm_sale_advertising_order/models/proof_delivery_list.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/report/__init__.py
nsm_sale_advertising_order/report/nsm_report.xml
nsm_sale_advertising_order/report/report_advertising_send_along_list.py
nsm_sale_advertising_order/report/report_credit_control_summary.xml
nsm_sale_advertising_order/report/report_indeellijst_list.py
nsm_sale_advertising_order/report/report_pndl_delivery_list.py
nsm_sale_advertising_order/report/report_saleorder.xml
nsm_sale_advertising_order/security/ir.model.access.csv
nsm_sale_advertising_order/views/advertising_issue_view.xml
nsm_sale_advertising_order/views/circulation_type_view.xml
nsm_sale_advertising_order/views/menuitem.xml
nsm_sale_advertising_order/views/product_view.xml
nsm_sale_advertising_order/views/proof_delivery_list_view.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml
nsm_sale_advertising_order/wizard/__init__.py
nsm_sale_advertising_order/wizard/adv_line_invoice.py
nsm_sale_advertising_order/wizard/credit_control_communication.py
nsm_sale_advertising_order/wizard/sale_line_create_multi.py

Added module with changes

---

misset_indeellijst/__init__.py
misset_indeellijst/__manifest__.py
misset_indeellijst/models/__init__.py
misset_indeellijst/models/sale_advertising.py
misset_indeellijst/report/__init__.py
misset_indeellijst/report/nsm_report.xml
misset_indeellijst/report/report_indeellijst_list.py
misset_indeellijst/views/sale_advertising_view.xml

make seperate module

---

credit_card_expenses/models/company.py
credit_card_expenses/models/hr_expense.py
credit_card_expenses/security/hr_expense_security.xml
credit_card_expenses/views/hr_expense_views.xml
credit_card_expenses/views/menu_view.xml
misset_crm/__init__.py
misset_crm/__manifest__.py
misset_crm/views/res_partner_view.xml
misset_sale_advertising_order/__init__.py
misset_sale_advertising_order/__manifest__.py
misset_sale_advertising_order/views/sale_advertising_order_view.xml

made changes

---

misset_reports/__init__.py
misset_reports/__manifest__.py
misset_reports/models/__init__.py
misset_reports/models/models.py
misset_reports/report/report_credit_control_summary.xml
misset_reports/report/report_invoice.xml
misset_reports/security/ir.model.access.csv
misset_reports/views/report.xml

T0245 - Misset QWEB & Template Layout
Module: misset_report

T0245 - Misset QWEB & Template Layout

---

misset_supplier_bank_access/views/res_partner_view.xml

Fix bank fields view 
Module: misset_supplier_full_access

 Fix bank fields view 

---

misset_expenses/__init__.py
misset_expenses/__manifest__.py
misset_expenses/models/__init__.py
misset_expenses/models/account.py
misset_expenses/models/hr_expense.py
misset_expenses/views/account_views.xml
misset_expenses/views/hr_expense_views.xml

T0255 - Misset analytic account department relation
Module: misset_expense

T0255 - Misset analytic account department relation

---

misset_indeellijst/__manifest__.py
misset_indeellijst/models/sale_advertising.py

T0259 - Material_status for sale.order.line recurring = TRUE
Module: misset_expense

T0259 - Material_status for sale.order.line recurring = TRUE

---

misset_indeellijst/models/sale_advertising.py

T0262 - Material_status for invoiced sale.order.line

T0262 - Material_status for invoiced sale.order.line

---

credit_card_expenses/__manifest__.py
credit_card_expenses/views/hr_expense_views.xml
credit_card_expenses/views/menu_view.xml

T0201 - Expense module changes, feedback on 08-05-2019
Module: credit_card_expenses

 T0201 - Expense module changes, feedback on 08-05-2019

---

misset_account/report/report_saleorderlines_document_nsm.xml
misset_crm/views/res_partner_view.xml
misset_sale_advertising_order/views/sale_advertising_order_view.xml

Several customisations for Misset in sale order report, res.partner TreeView and sale order TreeView.

Several customisations for Misset in sale order report, res.partner TreeView and sale order TreeView.

---

misset_indeellijst/__manifest__.py
misset_indeellijst/models/sale_advertising.py

T0259 - if reccuring is false set recurring_id False
- update similar status for lines added as recurring_id

T0259 - if reccuring is false set recurring_id False - update similar status for lines added as recurring_id

---

misset_indeellijst/views/sale_advertising_view.xml

T0263 - Customer sort Indeellijst

T0263 - Customer sort Indeellijst

---

misset_indeellijst/views/sale_advertising_view.xml

T0263 - Customer sort Indeellijst Added order_advertiser_id

T0263 - Customer sort Indeellijst Added order_advertiser_id

---

credit_card_expenses/models/hr_expense.py
misset_bewijsnummerlijst/report/report_pndl_delivery_list.py

Task: fix singleton error on hr_timesheet_sheet write object, (Fwd: decl batch Pay 0061)
Module: credit_card_expenses

Task: fix singleton error on hr_timesheet_sheet write object, (Fwd: decl batch Pay 0061)

---

misset_indeellijst/views/sale_advertising_view.xml

Removed some double columns from Indeellijst

laatste keer hoop ik :O

---

misset_crm/views/res_partner_view.xml

misset_crm : T0281 - Customised customer TreeView for Misset

misset_crm : T0281 - Customised customer TreeView for Misset

---

misset_reports/report/report_credit_control_summary.xml

Task: T0284 - Misset invoice layout and credit control layout changes
Module: misset_reports

Task: T0284 - Misset invoice layout and credit control layout changes

---

misset_crm/__manifest__.py
misset_indeellijst/views/sale_advertising_view.xml

misset_indeellijst: T0257 - Customised Indeellijst TreeView for Misset - last changes

misset_indeellijst: T0257 - Customised Indeellijst TreeView for Misset - last changes

---

misset_sale_advertising_order/views/sale_advertising_order_view.xml

misset_sale_advertising_order: T0249 - Changes in Overzicht advertentie orderregels TreeView for Misset

misset_sale_advertising_order: T0249 - Changes in Overzicht advertentie orderregels TreeView for Misset

---

misset_indeellijst/__manifest__.py
misset_indeellijst/views/sale_advertising_view.xml

misset_indeellijst: T0257 - Customised Indeellijst TreeView for Misset

misset_indeellijst: T0257 - Customised Indeellijst TreeView for Misset

---

misset_bewijsnummerlijst/report/report_pndl_delivery_list.py

Task: T0279 - Fix misset unicode PNDL encoding
Module: misset_bewijsnummerlijst

Task: T0279 - Fix misset unicode PNDL encoding

---

misset_crm/views/res_partner_view.xml

misset_crm: T0325 - Allow editing category_ids in res.partner for all sales users

misset_crm: T0325 - Allow editing category_ids in res.partner for all sales users

---

misset_2step_validation/models/account_invoice.py

T0318 - Prevent vendor invoices with 0 amount to enter workflow
Module: misset_2step_validation

T0318 - Prevent vendor invoices with 0 amount to enter workflow

---

misset_sale_advertising_order/models/sale_advertising.py
misset_sale_advertising_order/views/sale_advertising_order_view.xml

T0334 - Bug fix: button "Submit for Approval" is not visible for sales users!

T0334 - Bug fix: button "Submit for Approval" is not visible for sales users!

---

misset_sale_advertising_order/models/sale_advertising.py

Task: T0254 - Add warning message order can't be modify by user once submitted

Task: T0254 - Add warning message order can't be modify by user once submitted

---

misset_sale_advertising_order/models/sale_advertising.py

Task: T0254 Feedback 29/07/2019

T0254 Feedback 29/07/2019

---

misset_sale_advertising_order/models/sale_advertising.py

Task: FIX, multi line order for regular sales users

Task: FIX, multi line order for regular sales users

---

misset_2step_validation/models/account_invoice.py

Task: FIX, task 318 to approve refund amount
Module: misset_2step_validation

Task: FIX, task 318 to approve refund amount

---

misset_2step_validation/models/account_invoice.py

Task: FIX, task 318 set verified invoices to paid in amount is zero
Module: misset_2step_validation

 Task: FIX, task 318 set verified invoices to paid in amount is zero

---

misset_sale_advertising_order/models/sale_advertising.py

FIX - Filter for advertising order

FIX- Filter for advertising order

---

misset_indeellijst/views/sale_advertising_view.xml

T0350 - Indeellijst filters - extra

T0350 - Indeellijst filters - extra

---

misset_2step_validation/models/account_invoice.py

Module: misset_2step_validation

Fix: customer 0's invoice set as paid while validating 

---

credit_card_expenses/models/hr_expense.py
credit_card_expenses/views/hr_expense_views.xml
misset_expenses/models/hr_expense.py
misset_expenses/views/hr_expense_views.xml

Added expense analytic domain
-Added is credit expense donain to expense lines
Module: misset_expense, credit_card_expense

Added expense analytic domain & "is credit expense" donain to expense lines

---

misset_account/data/mail_template_data.xml
misset_activity_de_duplicate/__init__.py
misset_activity_de_duplicate/__manifest__.py
misset_activity_de_duplicate/data/cron_data.xml
misset_activity_de_duplicate/models/__init__.py
misset_activity_de_duplicate/models/crm_activity_de_duplicate.py
misset_activity_de_duplicate/models/mail_message.py
misset_activity_de_duplicate/views/crm_activity_de_duplicate_views.xml

T0374 - Remove duplicate email templates from Misset repo & T0421 - Bug fix: How to remove double message_ids records in crm.lead

---

misset_account/report/report_invoice.xml
misset_crm/views/res_partner_view.xml
misset_indeellijst/report/report_indeellijst_list.py
misset_sale_advertising_order/report/report_indeellijst_list.py

In view crm.lead.tree.opportunity Added another field: partner_contact_id

T0569 - Sales pipline view change

---

misset_maintenance/__init__.py
misset_maintenance/__manifest__.py
misset_maintenance/controllers/__init__.py
misset_maintenance/controllers/controllers.py
misset_maintenance/demo/demo.xml
misset_maintenance/models/__init__.py
misset_maintenance/models/models.py
misset_maintenance/security/ir.model.access.csv
misset_maintenance/security/security.xml
misset_maintenance/views/templates.xml
misset_maintenance/views/views.xml

new menu called "Maintenance" , in this menu we'd like a sub menu with user defined filters,
where all filters of other users should be visible, and delectable
visible to the group Beheer - Aanpassen Filters

new menu called Maintenance

---

misset_sale_advertising_order/models/sale_advertising.py

Update order line start and end date when issue date changes

---

misset_sale_advertising_order/models/sale_advertising.py

Update payer from advertiser

---

misset_sale_advertising_order/models/sale_advertising.py

Update payer from advertiser & allow payer to reset

---

misset_account/report/report_invoice.xml
misset_sale_advertising_order/models/sale_advertising.py

Module:misset_sale_advertising_order

Reverting issue date commit already available in nsm_sale_advertising_order
